name: E2E CI

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    cypress:
        name: Cypress E2E tests
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup env
              run: |
                  cat <<EOT >> .env
                  DATABASE_URL=postgresql://postgres:password@localhost:5432/postgres
                  SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
                  MULTI_TENANCY=true
                  JWT_SECRET=NtDi6p47sZoi8oBUevWLyTSvl4K9SPVX
                  NEXT_PUBLIC_OPT_OUT_TRACKING=true
                  API_DOMAIN=http://localhost:3000
                  EOT

            - name: Start stack with Docker Compose
              run: |
                  docker-compose -f docker-compose.yml down
                  docker-compose -f docker-compose.yml up -d

            - name: Cypress run
              uses: cypress-io/github-action@v4
              with:
                  browser: chrome
                  build: yarn build
                  start: |
                      yarn start
                  command: yarn test:e2e

            - name: Archive test screenshots
              uses: actions/upload-artifact@v3
              with:
                  name: screenshots
                  path: cypress/screenshots
              if: ${{ failure() }}

            - name: Archive test downloads
              uses: actions/upload-artifact@v3
              with:
                  name: downloads
                  path: cypress/downloads
              if: ${{ failure() }}

            - name: Archive test videos
              uses: actions/upload-artifact@v3
              with:
                  name: videos
                  path: cypress/videos
              if: ${{ failure() }}

            - name: Show logs on failure
              # use artefact here, as I think the output will be too large for display in an action
              uses: actions/upload-artifact@v3
              with:
                  name: logs
                  path: /tmp/logs
              if: ${{ failure() }}
