name: docker-release

on:
    push:
        branches:
            - 'master'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: posthog/squeak:latest
                  context: '{{defaultContext}}:packages/squeak'
                  build-args: |
                      SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}

            - name: Deploy app
              env:
                  DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
                  DO_APP_ID: ${{ secrets.DO_APP_ID }}
              run: |
                  curl -X POST -H "Authorization: Bearer $DO_API_TOKEN" https://api.digitalocean.com/v2/apps/$DO_APP_ID/deployments
